language: rust
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
#  allow_failures:
#    - rust: nightly
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      before_script:
        - rustup target add wasm32-unknown-unknown --toolchain nightly
        - nvm install 8.2.1
        - npm install
        - ./build
      script:
        - npm run test
